# Generated by Django 2.0 on 2017-12-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('sub_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=257)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('last_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Pss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Purchase'),
        ),
        migrations.AlterUniqueTogether(
            name='product_pss',
            unique_together={('product', 'date')},
        ),
    ]
